name: 'connvertpay'

volumes:
  postgres-data:
  prometheus-data:

networks:
  connvertpay-network:
    driver: bridge

services:
  postgres:
    container_name: connvertpay-postgres
    image: postgres:16.3-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=connvertpay-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_INITDB_ARGS=--data-checksums
    ports:
      - "5432:5432"
    networks:
      - connvertpay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d connvertpay-db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
      -c log_statement=all
      -c log_min_duration_statement=100
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
      -c log_checkpoints=on
      -c log_connections=on
      -c log_disconnections=on
      -c log_lock_waits=on
